### ISSUE TITLE
get going again

### ISSUE THREAD

**Issue by nicferrier** [xymostech/ErMinecraft#1]
Why have you abandoned this? it's an awesome idea!

**Comment by meme** [comment]
https://github.com/meme/certain-elephant, It's been updated to add rebar3 and Erlang 18 compatibility along with distributing a map so you can actually run it.

**Comment by xymostech** [comment]
@meme Cool! I'm glad my random one-off project from a while ago was useful :) (this repo is completely abandoned, so I'm gonna close this)
